version: '3.8'
services:
  client:
    container_name: client
    env_file:
      - .env
    build:
      context: ./
    command: npm start
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"

