export const NOTIFICATION_ACTIONS = {
    SHOW_NOTIFICATION_ERROR: "SHOW_NOTIFICATION_ERROR",
    SHOW_NOTIFICATION_WARNING: "SHOW_NOTIFICATION_WARNING",
    SHOW_NOTIFICATION_SUCCESS: "SHOW_NOTIFICATION_SUCCESS",
    HIDE_NOTIFICATION:"HIDE_NOTIFICATION"
}